#!/usr/bin/env bash
# Scripts that tranfers a file from our client to a server

path=$1
server=$2
user=$3
private_key=$4

if [ $# -lt 3 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    scp -i "$private_key" -o StrictHostKeyChecking=no "$path" "$user"@"$server":~/
fi
