#!/usr/bin/env bash
# Configures nginx
sudo apt-get update -y
sudo apt-get install nginx -y

# Replace the default NGINX page content with "Hello World!"
echo "Hello World!" > /var/www/html/index.nginx-debian.html

sudo service nginx restart
