#!/usr/bin/env bash
# Configures nginx
sudo apt-get update -y
sudo apt-get install nginx -y

# Replace the default NGINX page content with "Hello World!"
echo "Hello World!" | sudo tee /var/www/html/index.html

sudo sed "/server_name/a\
location /redirect_me {\
return 301 https://youtube.com;\
}" /etc/nginx/sites-available/default 

sudo service nginx restart
