#!/usr/bin/env bash
# Configures a new Ubuntu machine with HAproxy as a load-balancer
# Configure HAproxy to send traffic to 2 web servers using round-robin

# Install Haproxy
sudo apt update -y

sudo add-apt-repository ppa:vbernat/haproxy-3.0 -y

sudo apt install haproxy -y

# Configure HAproxy to balance traffic between 2 servers
sudo tee -a /etc/haproxy/haproxy.cfg << END

# Frontend: Receives incoming traffic
frontend http_front
        bind *:80
        default_backend backend_servers

# Backend: Distributes traffic among multiple servers
backend backend_servers
        balance roundrobin
        server web-01 35.174.185.171:80 check
        server web-02 54.160.109.229:80 check
END
