#!/usr/bin/env bash
# Configure nginx to listen on port 80 and kill the process ( so the init deamon will flag it as off)
sudo sed -i 's/8080/80/' /etc/nginx/sites-enabled/default
sudo  service nginx restart
sudo rm -f /run/nginx.pid
