#!/usr/bin/env bash
#Script that displays numbers 1-20, displays 4 then 
#"bad luck from china" for the 4th loop, 9 then "bad luck from japan"
#for the 9th loop and displays 17 then "bad luck from italy" for 17th 

i=1
while [ $i -lt 21 ]
do
	case $i in
		4)
			echo "$i"
			echo "bad luck from China"
			;;
		9)
			echo "$i"
			echo "bad luck in Japan"
			;;
		17)
			echo "$i"
			echo "bad luck in Italy"
			;;
		*)
			echo "$i"
			;;
	esac
	i=$((i + 1))
done
