#!/usr/bin/env bash
# Script that creates an RSA key pair
KEY_NAME="school"
KEY_BITS=4096
PASSPHRASE="betty"

# Create the RSA key pair
ssh-keygen -t rsa -b "$KEY_BITS" -N "$PASSPHRASE" -f "$KEY_NAME"
